namespace: lantronix
name: oob
version: 1.0.2
readme: README.md
description: Ansible collection for Lantronix Out-of-Band infrastructure (SLC 9000 + Percepxion)
license:
  - Apache-2.0
authors:
  - Lantronix Product Team <ansible@lantronix.com>
repository: https://github.com/What-Is-Phase-Two/ansible-collection-oob
documentation: https://github.com/What-Is-Phase-Two/ansible-collection-oob/tree/main/docs
homepage: https://www.lantronix.com
issues: https://github.com/What-Is-Phase-Two/ansible-collection-oob/issues
tags:
  - networking
  - oob
  - lantronix
  - percepxion
  - console-server
  - slc9000
  - serial-console
dependencies:
  ansible.netcommon: ">=5.0.0"
